Users edit application
poppo4444/chat-space pull request #7
Opened 2017-06-13 04:12 UTC by poppo4444

2017-06-13 04:20 UTC, yusukeyamane commented
# What

# Why
は確実に記載しましょう

2017-06-13 04:20 UTC, yusukeyamane commented on app/controllers/users_controller.rb
> +  def update
これでアップデート出来ていますか？

2017-06-14 02:22 UTC, tatsuya4150 requested changes

2017-06-14 02:22 UTC, tatsuya4150 commented on app/controllers/users_controller.rb
> +    current_user.update(user_params)
更新のできなかった場合の処理も書いたほうがいいです。

2017-06-14 11:34 UTC, yusukeyamane commented on app/controllers/users_controller.rb
> +    if
if ”条件分岐”という風に記述しましょう

2017-06-14 11:35 UTC, yusukeyamane commented on app/controllers/users_controller.rb
> +  private
privateの下には空行を入れましょう

2017-06-14 11:36 UTC, yusukeyamane commented on Gemfile
>    gem 'devise'
deviseは全ての環境で使用するのでこのブロックからは外に出しましょう

2017-06-15 04:28 UTC, kyohei0423 commented on db/migrate/20170612072344_add_name_to_users.rb
> +    add_column :users, :name, :string
null false制約とユニーク制約もつけましょう

2017-06-15 04:28 UTC, kyohei0423 commented on db/migrate/20170612072344_add_name_to_users.rb
> +    add_column :users, :name, :string
バリデーションの追加もお願いします

2017-06-15 05:43 UTC, kenchantandf commented on app/controllers/users_controller.rb
> +    params.require(:user).permit(:name, :email)
name ,email以外にも編集したい場合はどうするのでしょうか？この二つ以外にも編集できなければいけないものがあるのでは？

2017-06-15 05:43 UTC, kenchantandf commented on app/controllers/users_controller.rb
> +    if  current_user.update(user_params)
flash messageの実装も一緒にしちゃうと楽かもしれませんね！

2017-06-15 05:43 UTC, kenchantandf commented on app/controllers/users_controller.rb
> +  def edit
editで@userの変数定義しないでも大丈夫ですか？

2017-06-15 05:43 UTC, kenchantandf commented on config/routes.rb
> +  resources :users, :only => [:update,:edit]
=>よりもコロンを使った書き方のほうが現代的なので、そちらに直しましょう！

2017-06-15 06:13 UTC, poppo4444 commented on app/controllers/users_controller.rb
> +    if  current_user.update(user_params)
カリキュラム通りにやるとブランチ切らないといけないと思ってたんですが、一緒にやってもいいんでしょうか・・・？

2017-06-15 06:18 UTC, ebkn12 commented on config/routes.rb
> +  resources :users, only: [:update,:edit]
OKです！ちなみに、
`:only => []`の書き方をハッシュロケット
`only: []`の書き方をキーワード引数
と言います。気になったら調べてみてください！

2017-06-15 06:23 UTC, poppo4444 commented on config/routes.rb
> +  resources :users, only: [:update,:edit]
ありがおとうございます！！
調べてみます

2017-06-15 06:24 UTC, merged